@anon_key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs
@user = me@email.com
@password = 123456

# this will change login or signup
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjU3MTk1NzY4LCJzdWIiOiJiYmIxNjZiNy1hNDYwLTQ1MzYtODkyYS0zMjc5ODVmN2Q0MTYiLCJlbWFpbCI6Im1lQGVtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnt9LCJyb2xlIjoiYXV0aGVudGljYXRlZCJ9.XwNPxdqGKskfyB1yp7Q5Z_g4XzI6yugFN6BTMI6fO1s

@user_id = bbb166b7-a460-4536-892a-327985f7d416

@ml_pgrest_host = {{$dotenv %ML_PGREST_HOST }}
@ml_pgrest_user = {{$dotenv %ML_PGREST_USER }}
@ml_pgrest_password = {{$dotenv %ML_PGREST_PASSWORD }}
@ml_pgrest_port = {{$dotenv %ML_PGREST_PORT }}
@ml_pgrest_token = {{$dotenv %ML_PGREST_TOKEN }}

### SIGNUP

POST http://localhost:54321/auth/v1/signup
Content-Type: application/json
apikey: {{anon_key}}

{
  "email": "{{user}}",
  "password": "{{password}}"
}

### LOGIN

POST http://localhost:54321/auth/v1/token?grant_type=password
Content-Type: application/json
apikey: {{anon_key}}

{
  "email": "{{user}}",
  "password": "{{password}}"
}

### invoke function get 100 trees

POST http://localhost:54321/functions/v1/trees?limit=100
Content-Type: application/json
apikey: {{anon_key}}
Authorization: Bearer {{access_token}}

### invoke function get specific tree

POST http://localhost:54321/functions/v1/trees?gml_id=eq.s_wfs_baumbestand_an.00008100:00283c82
Content-Type: application/json
apikey: {{anon_key}}
Authorization: Bearer {{access_token}}

### invoke function get join forcast
POST http://localhost:54321/functions/v1/trees?limit=100&select=forecast(baum_id)
Content-Type: application/json
apikey: {{anon_key}}
Authorization: Bearer {{access_token}}


############## ML pgrest


### login

POST {{ml_pgrest_host}}:{{ml_pgrest_port}}/rpc/login
Content-Type: application/json

{"email": "{{ml_pgrest_user}}", "password": "{{ml_pgrest_password}}"}



### get all trees

POST {{ml_pgrest_host}}:{{ml_pgrest_port}}/nowcast?limit=100
Content-Type: application/json
Authorization: Bearer {{ml_pgrest_token}}




